### PR TITLE
change UGI

### PR DESCRIPTION
**Pull request by crua9**
Changed the color of the background, text, text size, and button image
to make it easier to read

Notes are provided along with the hex code that was there before.

### CODE REVIEW

**Comment by mykevin81** [comment]
Thanks That actually looks great!!

**Comment by crua9** [comment]
No problem. You might want to change it from being a relative layout, and make it a vertical layout. You can use the gravity to help with the placement. 

The reason why you might want to do this change is because there is no way of knowing what size screen is going to be on someones phone. 

Also, I was going to remove the action bar stuff. But, I didn't know if you were using it. 
In a much bigger app, this will lower the download size and removing the useless code will make it easier with anyone that's coding.

**Comment by mykevin81** [comment]
How do you remove the action bar?
for setting, i was just going to use one float button

also for the tracker_activity
I'm trying put a top fragment and bottom fragment
top fragment has multiple boxes to display real time info of time, speed, etc
bottom fragment uses google maps fragment

Im doing the google maps fragments now~

**Comment by crua9** [comment]
I just sent another pull request. I took it out there, and I added a few notes.

**Pull request merged**
