### PR TITLE
Master

### PR DESCRIPTION
**Pull request by crua9**
Changed the Java action bar (took it out), made the UGI center on the front screen, and I made it quicker to go between screens.

### CODE REVIEW

**Comment by mykevin81** [comment]
Thanks it looks better
There is one problem however
when I press Start, the application force close

everything compiles fine though
looking for problem right now

**Comment by crua9** [comment]
That's odd. It works for me.

If you added something to the tracking page (JAVA or XML) try taking it off and trying again.

**Comment by mykevin81** [comment]
maybe, because I added a fragment with google maps in second activity.

I'll do a new checkout and add it manually

**Comment by crua9** [comment]
Google maps isn't on the emulators. You may have to hook up an Android phone and use it as your emulator.
That or use Geynmotion .

**Comment by mykevin81** [comment]
so yea the new checkout works
so I have to find a way to integrate the google maps into it
and yes I have a phone hooked up!!

**Pull request merged**
