### PR TITLE
Splash Screen and a few other changes

### PR DESCRIPTION
**Pull request by crua9**
I added a splash screen, and it works. The image does need to be change.

I left a bunch of comments on what I changed, and how to modify it.

### CODE REVIEW

**Comment by crua9** [comment]
I used the background as the splash image. I left notes under the XML splash layout on how to change it

**Comment by mykevin81** [comment]
that looks great! lol you doing it too fast, I'm having a little problem catching up.
But anyway, I was thinking at the start page include the google + login.

**Comment by mykevin81** [comment]
so that they can back up everything up to their drive

**Comment by crua9** [comment]
Lol, thanks. It's my last day of spring break, so I will be slowing down soon.

Anyways, Instead of just putting it only on the start screen. I wonder if there is a way to have a floating button for all the screens.
As far as syncing it to Google Drive. I never done that before, but I know it's possible. You will need to look at the restful code for Google.

BTW, instead of making this a biking only app. Why don't you make it into a biking and running app since it basically measures the speed and location.

**Comment by crua9** [comment]
Oh, and I have a bit of code that you can use on some apps I've already made. Most developers tend to keep their code somewhere, and that away they can paste and modify as needed.

For example, I basically just copy and pasted my splash screen code from another project to this one.

**Comment by mykevin81** [comment]
Oh we should use a list view for setting! and background should be white. just plain and simple

I am currently busy with other stuff, but I will change it when I have time

**Comment by crua9** [comment]
The background can easily be white by just taking off the background on the layout. But, I'm not sure how well a list view will work. One of the things I was trying to add is a section where you can tell the user how to use the application. 

I found a while back, grandparents are starting to use smartphones more and more. One of the biggest request you will get from them is a way to increase text size, change the color, and an area saying how you can use the app.
But at the end of the day, it's up to you if you want to have it as a list view.

As far as getting things done. I hear you there. I think you will find most people on github will try to help out when they get time, but more than not. People just disappear when they get busy

**Pull request merged**
